# Generated by Django 5.0.12 on 2025-03-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("InventoryManagementApp", "0006_remove_bill_item_name_remove_bill_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="gst_amount",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="without_gst",
        ),
        migrations.AlterField(
            model_name="billitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
