# Generated by Django 5.0.12 on 2025-03-03 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "InventoryManagementApp",
            "0007_remove_bill_gst_amount_remove_bill_without_gst_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="billitem",
            name="bill",
        ),
        migrations.DeleteModel(
            name="Buyer",
        ),
        migrations.DeleteModel(
            name="Bill",
        ),
        migrations.DeleteModel(
            name="BillItem",
        ),
    ]
